# Ejercicios Modulo 3. Clases y objetos

Consideraciones a tener en cuenta: 

* Guardar este documento con el siguiente formato para su entrega: __M3_01_nombre_apellido1_apellido2__
* Realizar los ejercicios con las herramientas vistas en las sesiones. 
* Comentar el código
* Utilizar nombres de variables apropiados, si vais a guardar una nota, llamar a esa variable nota, no n o x

# Ejercicio 1

#### Creación

* Crea una clase llamada __Alumno__ que tenga los atributos nombre y nota
* Crea el __constructor__ de la clase. Añadir en el constructor un print para informar de que el alumno se ha creado con éxito
* Sobreescribe el método **string (``__str__``)**, para que al imprimir por pantalla se vea su informacion
* Crear un método llamado __calificacion__ que imprima por pantalla si el alumno ha aprobado o suspendido en base a su nota

#### Experimentación

* Crea algunos alumnos
* Prueba a mostrar los objetos alumno y el método calificacion

In [40]:

# Defino la clase Alumno con los atributos nombre y nota
class Alumno:
    def __init__(self, nombre, nota):
        # Guardo el nombre y la nota del alumno
        self.nombre = nombre
        self.nota = nota
        
        # Informo que el alumno se ha creado correctamente
        print(f"Alumno {self.nombre} creado con éxito")

    # Sobrescribo el método __str__ para mostrar la información del alumno
    def __str__(self):
        return f"Alumno: {self.nombre} | Nota: {self.nota}"

    # Este método imprime si el alumno ha aprobado o suspendido
    def calificacion(self):
        if self.nota >= 5:
            print(f"{self.nombre} ha aprobado")
        else:
            print(f"{self.nombre} ha suspendido")


# Creo algunos alumnos para probar la clase
alumno1 = Alumno("Alba Agundez", 9.5)
alumno2 = Alumno("Yasin Benkssouba", 4.9)

alumnos = [alumno1, alumno2]

# Muestro los objetos alumno usando __str__
print("\nMostrando alumnos:")
for alumno in alumnos:
    print(alumno)

# Pruebo el método calificacion
print("\nProbando método calificacion:")
for alumno in alumnos:
    alumno.calificacion()


Alumno Alba Agundez creado con éxito
Alumno Yasin Benkssouba creado con éxito

Mostrando alumnos:
Alumno: Alba Agundez | Nota: 9.5
Alumno: Yasin Benkssouba | Nota: 4.9

Probando método calificacion:
Alba Agundez ha aprobado
Yasin Benkssouba ha suspendido


# Ejercicio 2

#### Creación

Sobre el ejercicio anterior realizar la siguiente modificación.

Si en el ejercicio hacemos un print(alumno1.nota) esto nos devolverá la nota del alumno. Esto puede llegar a ser un problema de seguridad, vamos a encapsular el código para que no podamos acceder directamente a las variables, y el acceso tenga que ser a través de métodos.

* Hacer que las variables de la clase sean __privadas__. Recordatorio: Añadir un guión delante del nombre de la variable
* Crea métodos __getter y setter__ para poder acceder y modificar las variables de la clase

#### Experimentación

* Crea algunos alumnos
* Comprueba que solo podamos acceder a las variables de la clase a través de sus métodos get y set

In [ ]:


# Defino la clase Alumno usando atributos “privados” con un guion bajo según el enunciado
class Alumno:
    def __init__(self, nombre, nota):
        # Guardo los datos del alumno con guion bajo para indicar que no se deben tocar directamente
        self._nombre = nombre
        self._nota = nota
        print(f"Alumno {self._nombre} creado con éxito")

    # Devuelvo el nombre cuando se imprime el objeto
    def __str__(self):
        return f"{self._nombre}"

    # Devuelvo si el alumno ha aprobado o suspendido según su nota
    def calificacion(self):
        if self._nota >= 5:
            return "Aprobado"
        else:
            return "Suspenso"

    # Devuelve el nombre usando un getter
    def get_nombre(self):
        return self._nombre

    # Permite cambiar el nombre usando un setter
    def set_nombre(self, nuevo_nombre):
        self._nombre = nuevo_nombre

    # Devuelve la nota usando un getter
    def get_nota(self):
        return self._nota

    # Permite cambiar la nota usando un setter
    def set_nota(self, nueva_nota):
        self._nota = nueva_nota


# Creo algunos alumnos para probar la clase
alumno1 = Alumno("Alba Agundez", 9.5)
alumno2 = Alumno("Yasin Benkssouba", 4.9)
alumnos = [alumno1, alumno2]

# Compruebo que accedo a la nota y al nombre solo usando getters y setters
for alumno in alumnos:
    print(alumno, f"Calificación {alumno.get_nota()} = {alumno.calificacion()}")

# Aquí modifico un dato usando setters para comprobar que funciona
alumno2.set_nota(6.0)
print("\nDespués de modificar la nota con setter:")
print(alumno2, f"Calificación {alumno2.get_nota()} = {alumno2.calificacion()}")



Alumno Alba Agundez creado con éxito
Alumno Yasin Benkssouba creado con éxito
Alba Agundez Calificación 9.5 = Aprobado
Yasin Benkssouba Calificación 4.9 = Suspenso

Después de modificar la nota con setter:
Yasin Benkssouba Calificación 6.0 = Aprobado


# Ejercicio 3

#### Creación

* Crea una clase llamada __Producto__ que tenga los atributos codigo, nombre, precio y tipo.
* Crea el __constructor__ de la clase. Añadir en el constructor un print para informar de que el producto se ha creado con éxito
* Crea métodos __getter y setter__ para acceder y modificar todos los atributos de la clase

#### Experimentación

* Crea algunos productos
* Prueba estos nuevos métodos que se han creado (getter y setter)

In [ ]:
# Defino la clase Producto para representar un producto tecnológico
class Producto:
    def __init__(self, codigo, nombre, precio, tipo):
        # Guardo los atributos del producto
        self._codigo = codigo
        self._nombre = nombre
        self._precio = precio
        self._tipo = tipo
        
        # Informo que el producto se ha creado correctamente
        print(f"Producto {self._nombre} creado con éxito")

    # Método para mostrar el producto en formato compacto
    def __str__(self):
        return f"{self._codigo} - {self._nombre} - {self._tipo} - {self._precio:.2f}€"

    # Getter del código
    def get_codigo(self):
        return self._codigo

    # Setter del código
    def set_codigo(self, nuevo_codigo):
        self._codigo = nuevo_codigo

    # Getter del nombre
    def get_nombre(self):
        return self._nombre

    # Setter del nombre
    def set_nombre(self, nuevo_nombre):
        self._nombre = nuevo_nombre

    # Getter del precio
    def get_precio(self):
        return self._precio

    # Setter del precio
    def set_precio(self, nuevo_precio):
        self._precio = nuevo_precio

    # Getter del tipo
    def get_tipo(self):
        return self._tipo

    # Setter del tipo
    def set_tipo(self, nuevo_tipo):
        self._tipo = nuevo_tipo



# Creo productos tecnológicos
producto1 = Producto(1, "Macbook Pro", 1000, "Informática")
producto2 = Producto(2, "iPhone 15", 1200, "Smartphone")
producto3 = Producto(3, "Monitor 27 pulgadas", 350, "Periférico")

# Los guardo en una lista
productos = [producto1, producto2, producto3]

# Muestro los productos usando __str__
print("\nMostrando productos:")
for producto in productos:
    print(producto)

# Pruebo getters
print("\nProbando getters:")
print(producto1.get_codigo(), producto1.get_nombre(), producto1.get_tipo(), f"{producto1.get_precio():.2f}€")

# Pruebo setters
print("\nProbando setters:")
producto1.set_precio(1100)
producto1.set_tipo("Oferta")

print(producto1.get_codigo(), producto1.get_nombre(), producto1.get_tipo(), f"{producto1.get_precio():.2f}€")



Producto Macbook Pro creado con éxito
Producto iPhone 15 creado con éxito
Producto Monitor 27 pulgadas creado con éxito

Mostrando productos:
1 - Macbook Pro - Informática - 1000.00€
2 - iPhone 15 - Smartphone - 1200.00€
3 - Monitor 27 pulgadas - Periférico - 350.00€

Probando getters:
1 Macbook Pro Informática 1000.00€

Probando setters:
1 Macbook Pro Oferta 1100.00€


# Ejercicio 4

#### 🛒 **Ampliación del Ejercicio de Productos**

Sigamos mejorando nuestro sistema de gestión de productos. En este ejercicio, ampliaremos la clase `Producto` para hacerla más funcional y eficiente.

1. **Sobrescribir el método `__str__()`**  
   - Ahora, al imprimir un objeto `Producto`, mostrará todos sus datos de forma clara y estructurada.  
   - **Ejemplo de salida esperada:**  
     ```
     Código: 1
     Nombre: Macbook Pro
     Precio: 1000€
     Tipo: Informática
     ```
   
2. **Crear el método `calcular_total(unidades)`**  
   - Recibe un número de unidades del producto.  
   - Calcula y devuelve el precio total de esas unidades.  
   - **Ejemplo de uso:**  
     ```python
     p1 = Producto(1, "Macbook Pro", 1000, "Informática")
     print(p1.calcular_total(5))  # Devuelve 5000
     ```

#### Experimentación

1. **Crea varios productos y prueba a imprimirlos** usando `print()`.  
2. **Calcula el precio total de varias unidades** de diferentes productos.  
3. **Modifica valores usando los setters** y observa cómo cambian los resultados.  


In [5]:
# Defino la clase Producto como ampliación del ejercicio 3
class Producto:
    def __init__(self, codigo, nombre, precio, tipo):
        # Guardo los atributos del producto
        self._codigo = codigo
        self._nombre = nombre
        self._precio = precio
        self._tipo = tipo

        # Informo que el producto se ha creado correctamente
        print(f"Producto {self._nombre} creado con éxito")

    # Sobrescribo __str__ para mostrar el producto con sus datos en formato estructurado
    def __str__(self):
        return (
            f"Código: {self._codigo}\n"
            f"Nombre: {self._nombre}\n"
            f"Precio: {self._precio:.2f}€\n"
            f"Tipo: {self._tipo}"
        )

    # Devuelve el código del producto
    def get_codigo(self):
        return self._codigo

    # Permite modificar el código del producto
    def set_codigo(self, nuevo_codigo):
        self._codigo = nuevo_codigo

    # Devuelve el nombre del producto
    def get_nombre(self):
        return self._nombre

    # Permite modificar el nombre del producto
    def set_nombre(self, nuevo_nombre):
        self._nombre = nuevo_nombre

    # Devuelve el precio del producto
    def get_precio(self):
        return self._precio

    # Permite modificar el precio del producto
    def set_precio(self, nuevo_precio):
        self._precio = nuevo_precio

    # Devuelve el tipo del producto
    def get_tipo(self):
        return self._tipo

    # Permite modificar el tipo del producto
    def set_tipo(self, nuevo_tipo):
        self._tipo = nuevo_tipo

    # Calcula y devuelve el precio total según las unidades
    def calcular_total(self, unidades):
        return self._precio * unidades


# Creo varios productos tecnológicos
producto1 = Producto(1, "Macbook Pro", 1000, "Informática")
producto2 = Producto(2, "iPhone 15", 1200, "Smartphone")
producto3 = Producto(3, "Monitor 27 pulgadas", 350, "Periférico")

# Los guardo en una lista para imprimirlos con un bucle
productos = [producto1, producto2, producto3]

# Muestro los productos usando print() para comprobar que __str__ funciona
print("\nMostrando productos con __str__():\n")
for producto in productos:
    print(producto)
    print()

# Calculo el total de distintas unidades para comprobar calcular_total
print("Calculando precio total por unidades:\n")
print(f"{producto1.get_nombre()} x 5 unidades = {producto1.calcular_total(5):.2f}€")
print(f"{producto2.get_nombre()} x 2 unidades = {producto2.calcular_total(2):.2f}€")
print(f"{producto3.get_nombre()} x 3 unidades = {producto3.calcular_total(3):.2f}€")

# Modifico valores con setters y vuelvo a calcular para ver el cambio reflejado
print("\nModificando valores con setters y comprobando cambios:\n")
producto1.set_precio(1100)
producto1.set_tipo("Oferta")

print(producto1)
print(f"\nNuevo total de {producto1.get_nombre()} x 5 unidades = {producto1.calcular_total(5):.2f}€")


Producto Macbook Pro creado con éxito
Producto iPhone 15 creado con éxito
Producto Monitor 27 pulgadas creado con éxito

Mostrando productos con __str__():

Código: 1
Nombre: Macbook Pro
Precio: 1000.00€
Tipo: Informática

Código: 2
Nombre: iPhone 15
Precio: 1200.00€
Tipo: Smartphone

Código: 3
Nombre: Monitor 27 pulgadas
Precio: 350.00€
Tipo: Periférico

Calculando precio total por unidades:

Macbook Pro x 5 unidades = 5000.00€
iPhone 15 x 2 unidades = 2400.00€
Monitor 27 pulgadas x 3 unidades = 1050.00€

Modificando valores con setters y comprobando cambios:

Código: 1
Nombre: Macbook Pro
Precio: 1100.00€
Tipo: Oferta

Nuevo total de Macbook Pro x 5 unidades = 5500.00€


Ampliación

# Ejercicio 5

#### 🛒 **Clase `Pedido` con un Objeto dentro**

En este ejercicio trabajaremos con **objetos dentro de objetos**, como hemos visto en ejemplos previos con `Pelicula` y `Director`, o `Catalogo` y `Pelicula`.  

Crearemos una clase `Pedido`, que representará un pedido de un cliente en una tienda.  
Uno de sus atributos será un **objeto de otra clase**, simulando la relación entre entidades en un sistema real.  

##### **Características del ejercicio**

1. **Clase `Cliente`**  
   - `nombre` (nombre del cliente)  
   - `direccion` (dirección del cliente)  
   - `telefono` (teléfono del cliente)  

2. **Clase `Pedido`**  
   - `codigo` (número identificador del pedido)  
   - `producto` (nombre del producto)  
   - `cantidad` (cantidad de productos pedidos)  
   - `precio_unitario` (precio por unidad del producto)  
   - `cliente` (**objeto de la clase `Cliente`**)  

3. **Métodos a implementar en Pedido**  
   - `__str__()` → Para imprimir la información del pedido con los datos del cliente incluidos.  
   - `calcular_total()` → Devuelve el precio total del pedido (`cantidad * precio_unitario`).  

##### **Experimentación**
1. **Crea un cliente y un pedido asociado.**  
2. **Muestra la información del pedido usando `print()`.**  
3. **Calcula el total del pedido.**  
4. **Modifica los datos del pedido y del cliente desde el pedido** (es decir, cambia el `nombre`, `dirección` o `teléfono` del cliente desde la instancia de `Pedido`).  
5. **Vuelve a mostrar la información actualizada para verificar los cambios.**   

**Salida esperada:**
```python
Información del pedido:
Pedido #101
Producto: Ordenador portátil
Cantidad: 2
Precio Unitario: 750€
Total: 1500€

Cliente: Juan Pérez
Dirección: Calle Mayor 123, Madrid
Teléfono: 666123456

Total del pedido:
Total a pagar: 1500€

Modificando datos del cliente desde el pedido:

Información del pedido actualizada:
Pedido #101
Producto: Ordenador portátil
Cantidad: 2
Precio Unitario: 750€
Total: 1500€

Cliente: Carlos López
Dirección: Avenida Sol 456, Barcelona
Teléfono: 654987321
```

In [8]:
# Creo la clase Cliente porque un pedido siempre pertenece a una persona
class Cliente:
    def __init__(self, nombre, direccion, telefono):
        # Aquí guardo los datos básicos del cliente
        self._nombre = nombre
        self._direccion = direccion
        self._telefono = telefono

    # Devuelve el nombre del cliente
    def get_nombre(self):
        return self._nombre

    # Permite cambiar el nombre si fuese necesario
    def set_nombre(self, nuevo_nombre):
        self._nombre = nuevo_nombre

    # Devuelve la dirección del cliente
    def get_direccion(self):
        return self._direccion

    # Permite actualizar la dirección
    def set_direccion(self, nueva_direccion):
        self._direccion = nueva_direccion

    # Devuelve el teléfono
    def get_telefono(self):
        return self._telefono

    # Permite modificar el teléfono
    def set_telefono(self, nuevo_telefono):
        self._telefono = nuevo_telefono


# Ahora creo la clase Pedido, que contiene un cliente dentro
class Pedido:
    def __init__(self, codigo, producto, cantidad, precio_unitario, cliente):
        # Guardo los datos principales del pedido
        self._codigo = codigo
        self._producto = producto
        self._cantidad = cantidad
        self._precio_unitario = precio_unitario
        
        # Aquí es donde usamos un objeto dentro de otro
        self._cliente = cliente

    # Este método calcula el total multiplicando cantidad por precio
    def calcular_total(self):
        return self._cantidad * self._precio_unitario

    # Sobrescribo __str__ para que al hacer print(pedido) salga todo formateado
    def __str__(self):
        return (
            f"Pedido #{self._codigo}\n"
            f"Producto: {self._producto}\n"
            f"Cantidad: {self._cantidad}\n"
            f"Precio Unitario: {self._precio_unitario:.0f}€\n"
            f"Total: {self.calcular_total():.0f}€\n\n"
            f"Cliente: {self._cliente.get_nombre()}\n"
            f"Dirección: {self._cliente.get_direccion()}\n"
            f"Teléfono: {self._cliente.get_telefono()}"
        )


# Creo un cliente
cliente1 = Cliente("Juan Pérez", "Calle Mayor 123, Madrid", "666123456")

# Creo un pedido asociado a ese cliente
pedido1 = Pedido(101, "Ordenador portátil", 2, 750, cliente1)

print("Información del pedido:")
print(pedido1)

print("\nTotal del pedido:")
print(f"Total a pagar: {pedido1.calcular_total():.0f}€")

print("\nModificando datos del cliente desde el pedido:\n")

# Cambio los datos del cliente desde el propio pedido
pedido1._cliente.set_nombre("Carlos López")
pedido1._cliente.set_direccion("Avenida Sol 456, Barcelona")
pedido1._cliente.set_telefono("654987321")

print("Información del pedido actualizada:")
print(pedido1)


Información del pedido:
Pedido #101
Producto: Ordenador portátil
Cantidad: 2
Precio Unitario: 750€
Total: 1500€

Cliente: Juan Pérez
Dirección: Calle Mayor 123, Madrid
Teléfono: 666123456

Total del pedido:
Total a pagar: 1500€

Modificando datos del cliente desde el pedido:

Información del pedido actualizada:
Pedido #101
Producto: Ordenador portátil
Cantidad: 2
Precio Unitario: 750€
Total: 1500€

Cliente: Carlos López
Dirección: Avenida Sol 456, Barcelona
Teléfono: 654987321


# Ejercicio 6

### 🛒 **Ampliación: Clase `Pedido` con Múltiples Productos y Cantidades**

En este ejercicio ampliaremos el sistema de pedidos para **permitir que un pedido contenga múltiples productos**, en lugar de un solo producto.   

1. Una **lista de objetos `Producto`**, que almacenará los productos comprados.  
2. Una **lista de cantidades**, donde cada posición corresponderá a la cantidad de unidades compradas del producto en la misma posición en la lista de productos.

_Nota: Cuando tenemos atributos que son listas o similares en nuestras clases, no es necesario implementarles getters y setters._

##### **Características del ejercicio**

1. **Clase `Cliente`**  
   - `nombre` (nombre del cliente).  
   - `direccion` (dirección del cliente).  
   - `telefono` (teléfono del cliente).  

2. **Clase `Producto`**  
   - `codigo` (número identificador único del producto).  
   - `nombre` (nombre del producto).  
   - `precio_unitario` (precio por unidad).  

3. **Clase `Pedido` (Modificada)**  
   - `codigo` (número identificador del pedido).  
   - `cliente` (**objeto de la clase `Cliente`**).  
   - `productos` (**lista de objetos `Producto`**).  
   - `cantidades` (**lista de enteros**, cada número representa la cantidad de unidades del producto en la misma posición de la lista de productos).  

4. **Métodos a implementar en `Pedido`**  
   - `__str__()` → Para imprimir la información del pedido más general, un resumen.  
   - `mostrar_pedido()` → Para imprimir la información del pedido con los datos del cliente y todos los productos comprados con sus cantidades. 

##### **Experimentación**
1. **Crea un cliente, varios productos y un pedido (con un cliente, una lista de productos y una lista de cantidades).**  
2. **Muestra la información del pedido usando `print()`.**  
3. **Muestra la información del pedido usando `mostrar_pedido()`.**

**Pista para la creación:**
```python
# Para la creación de un pedido, es necesario crear previamente sus productos y cantidades:
productos_pedido = [producto1, producto2, producto3]
cantidades_pedido = [2, 1, 3]
```

**Salida esperada:**
```python
Información general del pedido usando __str__():
Pedido #101 | Cliente: Juan Pérez | Total productos: 6

Información detallada del pedido usando mostrar_pedido():
Pedido #101
Cliente: Juan Pérez

Productos en el pedido:
- Ordenador portátil x 2 unidades
- Ratón inalámbrico x 1 unidades
- Teclado mecánico x 3 unidades
```

In [9]:
# Primero creo la clase Cliente, que representa a la persona que hace el pedido
class Cliente:
    def __init__(self, nombre, direccion, telefono):
        # Guardamos los datos básicos del cliente
        self._nombre = nombre
        self._direccion = direccion
        self._telefono = telefono

    # Devuelve el nombre del cliente
    def get_nombre(self):
        return self._nombre

    # Devuelve la dirección del cliente
    def get_direccion(self):
        return self._direccion

    # Devuelve el teléfono del cliente
    def get_telefono(self):
        return self._telefono


# Ahora definimos la clase Producto, que representa cada artículo que se puede comprar
class Producto:
    def __init__(self, codigo, nombre, precio_unitario):
        # Cada producto tiene su código, nombre y precio por unidad
        self._codigo = codigo
        self._nombre = nombre
        self._precio_unitario = precio_unitario

    # Devuelve el nombre del producto
    def get_nombre(self):
        return self._nombre

    # Devuelve el precio unitario
    def get_precio_unitario(self):
        return self._precio_unitario


# Por último definimos la clase Pedido, que une cliente, productos y cantidades
class Pedido:
    def __init__(self, codigo, cliente, productos, cantidades):
        # Código identificador del pedido
        self._codigo = codigo

        # Objeto Cliente asociado al pedido
        self._cliente = cliente

        # Lista de objetos Producto
        self._productos = productos

        # Lista de cantidades (misma posición que los productos)
        self._cantidades = cantidades

    # Calcula el total del pedido multiplicando precio por cantidad
    def calcular_total(self):
        total = 0
        for producto, cantidad in zip(self._productos, self._cantidades):
            total += producto.get_precio_unitario() * cantidad
        return total

    # Devuelve el total de unidades del pedido
    def total_productos(self):
        return sum(self._cantidades)

    # Método que muestra un resumen general del pedido
    def __str__(self):
        return (
            f"Pedido #{self._codigo} | "
            f"Cliente: {self._cliente.get_nombre()} | "
            f"Total productos: {self.total_productos()}"
        )

    # Método que muestra toda la información detallada del pedido
    def mostrar_pedido(self):
        print(f"Pedido #{self._codigo}")
        print(f"Cliente: {self._cliente.get_nombre()}\n")
        print("Productos en el pedido:")

        # Recorremos productos y cantidades al mismo tiempo
        for producto, cantidad in zip(self._productos, self._cantidades):
            print(f"- {producto.get_nombre()} x {cantidad} unidades")


# Creamos el cliente
cliente = Cliente("Juan Pérez", "Calle Mayor 123, Madrid", "666123456")

# Creamos los productos
producto1 = Producto(1, "Ordenador portátil", 750)
producto2 = Producto(2, "Ratón inalámbrico", 65)
producto3 = Producto(3, "Teclado mecánico", 100)

# Creamos las listas necesarias para el pedido
productos_pedido = [producto1, producto2, producto3]
cantidades_pedido = [2, 1, 3]

# Creamos el pedido asociando cliente, productos y cantidades
pedido = Pedido(101, cliente, productos_pedido, cantidades_pedido)


# Mostramos el resumen general usando __str__()
print("Información general del pedido usando __str__():")
print(pedido)

print("\nInformación detallada del pedido usando mostrar_pedido():")
pedido.mostrar_pedido()



Información general del pedido usando __str__():
Pedido #101 | Cliente: Juan Pérez | Total productos: 6

Información detallada del pedido usando mostrar_pedido():
Pedido #101
Cliente: Juan Pérez

Productos en el pedido:
- Ordenador portátil x 2 unidades
- Ratón inalámbrico x 1 unidades
- Teclado mecánico x 3 unidades


# Ejercicio 7

### 🛒 **Ampliación: Clase `Pedido` con Múltiples Productos, Cálculo Total y Agregar Producto**

En este ejercicio ampliaremos el anterior ampliando las siguientes caracteristicas:

##### **Características del ejercicio**

1. **Nuevos Métodos en `Pedido`**   
   - `calcular_total()` → Calcula y devuelve el precio total del pedido.  
   - `agregar_producto(producto, cantidad)` → Permite añadir un nuevo producto al pedido.  

##### **Experimentación**
1. **Crea un cliente, varios productos y un pedido (con un cliente, una lista de productos y una lista de cantidades).**  
2. **Muestra la información del pedido usando `print()`.**  
3. **Muestra la información detallada del pedido con `mostrar_pedido()`.**  
4. **Calcula el total del pedido con `calcular_total()`.**
       Pista: Para esto tendrás que recorrer dos listas, la de productos y la de cantidades, como tienen el mismo tamaño, puedes usar el tamaño de cualquiera para recorrer ambas con el mismo índice.
6. **Agrega un nuevo producto al pedido con `agregar_producto()`.**  
7. **Vuelve a mostrar el pedido actualizado y calcula el nuevo total.**

**Salida esperada:**
```python
Información general del pedido usando __str__():
Pedido #101 | Cliente: Juan Pérez | Total productos: 6 | Total: 1765€

Información detallada del pedido usando mostrar_pedido():
Pedido #101
Cliente: Juan Pérez

Productos en el pedido:
- Ordenador portátil x 2 unidades
- Ratón inalámbrico x 1 unidades
- Teclado mecánico x 3 unidades

Total del pedido antes de agregar un nuevo producto:
Total: 1765€
----------------------------------------
 PRODUCTO AGREGADO
----------------------------------------
Información detallada del pedido después de agregar un nuevo producto:
Pedido #101
Cliente: Juan Pérez

Productos en el pedido:
- Ordenador portátil x 2 unidades
- Ratón inalámbrico x 1 unidades
- Teclado mecánico x 3 unidades
- Monitor Full HD x 1 unidades

Total del pedido despues de agregar un nuevo producto:
Total: 1965€
```

In [10]:
# Creo la clase Cliente para guardar los datos básicos de la persona que realiza el pedido
class Cliente:
    def __init__(self, nombre, direccion, telefono):
        self._nombre = nombre
        self._direccion = direccion
        self._telefono = telefono

    def get_nombre(self):
        return self._nombre


# Creo la clase Producto con su nombre y precio unitario
class Producto:
    def __init__(self, codigo, nombre, precio_unitario):
        self._codigo = codigo
        self._nombre = nombre
        self._precio_unitario = precio_unitario

    def get_nombre(self):
        return self._nombre

    def get_precio_unitario(self):
        return self._precio_unitario


# Clase Pedido ampliada: ahora permite múltiples productos
class Pedido:
    def __init__(self, codigo, cliente, productos, cantidades):
        self._codigo = codigo
        self._cliente = cliente
        self._productos = productos          # Lista de objetos Producto
        self._cantidades = cantidades        # Lista de cantidades (misma posición que productos)

    # Este método calcula el total recorriendo productos y cantidades al mismo tiempo
    def calcular_total(self):
        total = 0
        for producto, cantidad in zip(self._productos, self._cantidades):
            total += producto.get_precio_unitario() * cantidad
        return total

    # Permite añadir un nuevo producto al pedido
    def agregar_producto(self, producto, cantidad):
        self._productos.append(producto)
        self._cantidades.append(cantidad)

    # Devuelve un resumen general del pedido
    def __str__(self):
        total_productos = sum(self._cantidades)
        return (
            f"Pedido #{self._codigo} | "
            f"Cliente: {self._cliente.get_nombre()} | "
            f"Total productos: {total_productos} | "
            f"Total: {self.calcular_total()}€"
        )

    # Muestra la información detallada del pedido
    def mostrar_pedido(self):
        print(f"Pedido #{self._codigo}")
        print(f"Cliente: {self._cliente.get_nombre()}\n")
        print("Productos en el pedido:")

        for producto, cantidad in zip(self._productos, self._cantidades):
            print(f"- {producto.get_nombre()} x {cantidad} unidades")


# Creo cliente
cliente = Cliente("Juan Pérez", "Calle Mayor 123, Madrid", "666123456")

# Creo productos
producto1 = Producto(1, "Ordenador portátil", 700)
producto2 = Producto(2, "Ratón inalámbrico", 65)
producto3 = Producto(3, "Teclado mecánico", 100)

# Listas necesarias para el pedido
productos_pedido = [producto1, producto2, producto3]
cantidades_pedido = [2, 1, 3]

# Creo el pedido
pedido = Pedido(101, cliente, productos_pedido, cantidades_pedido)

print("Información general del pedido usando __str__():")
print(pedido)

print("\nInformación detallada del pedido usando mostrar_pedido():")
pedido.mostrar_pedido()

print("\nTotal del pedido antes de agregar un nuevo producto:")
print(f"Total: {pedido.calcular_total()}€")

print("\n--------------------------------")
print("PRODUCTO AGREGADO")
print("--------------------------------\n")

# Nuevo producto
producto4 = Producto(4, "Monitor Full HD", 200)

# Lo agrego al pedido
pedido.agregar_producto(producto4, 1)

print("Información detallada del pedido después de agregar un nuevo producto:")
pedido.mostrar_pedido()

print("\nTotal del pedido después de agregar un nuevo producto:")
print(f"Total: {pedido.calcular_total()}€")


Información general del pedido usando __str__():
Pedido #101 | Cliente: Juan Pérez | Total productos: 6 | Total: 1765€

Información detallada del pedido usando mostrar_pedido():
Pedido #101
Cliente: Juan Pérez

Productos en el pedido:
- Ordenador portátil x 2 unidades
- Ratón inalámbrico x 1 unidades
- Teclado mecánico x 3 unidades

Total del pedido antes de agregar un nuevo producto:
Total: 1765€

--------------------------------
PRODUCTO AGREGADO
--------------------------------

Información detallada del pedido después de agregar un nuevo producto:
Pedido #101
Cliente: Juan Pérez

Productos en el pedido:
- Ordenador portátil x 2 unidades
- Ratón inalámbrico x 1 unidades
- Teclado mecánico x 3 unidades
- Monitor Full HD x 1 unidades

Total del pedido después de agregar un nuevo producto:
Total: 1965€


# Ejercicio 8

### 🏡 **Ejercicio: Herencia Simple en un Sistema de Viviendas**

En este ejercicio trabajaremos con **herencia simple**, creando una clase base (padre) y dos clases derivadas (hijas).  

Aprenderemos a reutilizar atributos y métodos de la clase padre en sus clases hijas y a sobrescribir métodos cuando sea necesario.

##### **Características del ejercicio**

1. **Clase `Vivienda` (Clase Padre)**  
   - `direccion` (ubicación de la vivienda).  
   - `metros_cuadrados` (tamaño de la vivienda en m²).  
   - `precio` (precio de la vivienda en euros).  
   - Método `__str__()` que devuelve una descripción general de la vivienda.  

2. **Clases Hijas que Heredan de `Vivienda`**  
   - **`Casa`** → Tiene un atributo adicional `jardin` (booleano que indica si tiene jardín o no).  
   - **`Apartamento`** → Tiene un atributo adicional `piso` (número de planta en la que se encuentra).  

3. **Métodos en las Clases Hijas**  
   - Cada clase hija sobrescribirá `__str__()` para incluir su información específica.  

##### **Experimentación**
1. **Crea una `Casa` y un `Apartamento`.**  
2. **Imprime su información con `print()`.**  
3. **Modifica algunos atributos después de la creación.**  
4. **Vuelve a imprimir los objetos para ver los cambios reflejados.**

**Salida esperada:**
```python
Listado de viviendas:
Ubicación: Calle Mayor 123, Madrid | Tamaño: 150 m² | Precio: 250000€ | Tipo: Casa | Jardín: Sí
Ubicación: Avenida Central 45, Barcelona | Tamaño: 80 m² | Precio: 180000€ | Tipo: Apartamento | Piso: 5

Modificando atributos y mostrando nuevamente:
Ubicación: Calle Mayor 123, Madrid | Tamaño: 150 m² | Precio: 260000€ | Tipo: Casa | Jardín: Sí
Ubicación: Avenida Central 45, Barcelona | Tamaño: 80 m² | Precio: 180000€ | Tipo: Apartamento | Piso: 7
```

In [1]:
# Creo la clase Vivienda como “clase padre”, porque Casa y Apartamento comparten lo básico
class Vivienda:
    def __init__(self, direccion, metros_cuadrados, precio):
        # Guardo la información común que tendrá cualquier vivienda
        self._direccion = direccion
        self._metros_cuadrados = metros_cuadrados
        self._precio = precio

    # Devuelvo la dirección por si la necesito desde fuera
    def get_direccion(self):
        return self._direccion

    # Devuelvo los metros cuadrados
    def get_metros_cuadrados(self):
        return self._metros_cuadrados

    # Devuelvo el precio
    def get_precio(self):
        return self._precio

    # Permito cambiar la dirección si luego se corrige o se actualiza
    def set_direccion(self, nueva_direccion):
        self._direccion = nueva_direccion

    # Permito cambiar los metros cuadrados
    def set_metros_cuadrados(self, nuevos_metros):
        self._metros_cuadrados = nuevos_metros

    # Permito cambiar el precio (por ejemplo si se revaloriza)
    def set_precio(self, nuevo_precio):
        self._precio = nuevo_precio

    # Este __str__ sirve como base para que las clases hijas lo reutilicen
    def __str__(self):
        return (
            f"Ubicación: {self._direccion} | "
            f"Tamaño: {self._metros_cuadrados} m² | "
            f"Precio: {self._precio}€"
        )


# Creo Casa heredando de Vivienda para no repetir dirección, metros y precio
class Casa(Vivienda):
    def __init__(self, direccion, metros_cuadrados, precio, jardin):
        # Aquí llamo al constructor de Vivienda para rellenar la parte común
        super().__init__(direccion, metros_cuadrados, precio)
        # Jardin es lo extra que solo tiene una Casa
        self._jardin = jardin

    # Devuelvo si tiene jardín
    def get_jardin(self):
        return self._jardin

    # Permito cambiar si tiene jardín o no
    def set_jardin(self, nuevo_jardin):
        self._jardin = nuevo_jardin

    # Sobrescribo __str__ para añadir la parte específica de Casa
    def __str__(self):
        jardin_txt = "Sí" if self._jardin else "No"
        return f"{super().__str__()} | Tipo: Casa | Jardín: {jardin_txt}"


# Creo Apartamento heredando de Vivienda para aprovechar los atributos comunes
class Apartamento(Vivienda):
    def __init__(self, direccion, metros_cuadrados, precio, piso):
        # Parte común del apartamento (heredada)
        super().__init__(direccion, metros_cuadrados, precio)
        # Piso es lo extra que solo tiene un Apartamento
        self._piso = piso

    # Devuelvo el piso del apartamento
    def get_piso(self):
        return self._piso

    # Permito cambiar el piso (por ejemplo si estaba mal puesto)
    def set_piso(self, nuevo_piso):
        self._piso = nuevo_piso

    # Sobrescribo __str__ para añadir la parte específica del Apartamento
    def __str__(self):
        return f"{super().__str__()} | Tipo: Apartamento | Piso: {self._piso}"


# Creo una casa y un apartamento con los mismos datos de la salida esperada
casa = Casa("Calle Mayor 123, Madrid", 150, 250000, True)
apartamento = Apartamento("Avenida Central 45, Barcelona", 80, 180000, 5)

print("Listado de viviendas:")
print(casa)
print(apartamento)

print("\nModificando atributos y mostrando nuevamente:")

casa.set_precio(260000)
apartamento.set_piso(7)

print(casa)
print(apartamento)




Listado de viviendas:
Ubicación: Calle Mayor 123, Madrid | Tamaño: 150 m² | Precio: 250000€ | Tipo: Casa | Jardín: Sí
Ubicación: Avenida Central 45, Barcelona | Tamaño: 80 m² | Precio: 180000€ | Tipo: Apartamento | Piso: 5

Modificando atributos y mostrando nuevamente:
Ubicación: Calle Mayor 123, Madrid | Tamaño: 150 m² | Precio: 260000€ | Tipo: Casa | Jardín: Sí
Ubicación: Avenida Central 45, Barcelona | Tamaño: 80 m² | Precio: 180000€ | Tipo: Apartamento | Piso: 7


# Ejercicio 9

### 🏡 **Ejercicio: Ampliación del Sistema de Viviendas con Métodos Específicos**

En este ejercicio ampliaremos nuestro sistema de viviendas, agregando una **tercera clase hija** y métodos específicos para cada tipo de vivienda.

##### **Características del ejercicio**

1. **Clase `Vivienda` (Clase Padre)**  
   - `direccion` (ubicación de la vivienda).  
   - `metros_cuadrados` (tamaño de la vivienda en m²).  
   - `precio` (precio de la vivienda en euros).  
   - Método `__str__()` que devuelve una descripción general de la vivienda.  

2. **Clases Hijas que Heredan de `Vivienda`**  
   - **`Casa`** → Tiene un atributo adicional `jardin` (booleano que indica si tiene jardín o no).  
     - Método `tiene_jardin()` → Devuelve `"Esta casa tiene jardín"` o `"Esta casa no tiene jardín"`.  
   - **`Apartamento`** → Tiene un atributo adicional `piso` (número de planta en la que se encuentra).  
     - Método `es_penthouse()` → Devuelve `True` si está en el último piso.  
   - **`Chalet`** (Nueva Clase) → Tiene un atributo adicional `piscina` (booleano que indica si tiene piscina o no).  
     - Método `tiene_piscina()` → Devuelve `"Este chalet tiene piscina"` o `"Este chalet no tiene piscina"`.  

3. **Métodos en las Clases Hijas**  
   - Cada clase hija sobrescribirá `__str__()` para incluir su información específica.  
   - Se agregarán métodos específicos para cada tipo de vivienda.  

##### **Experimentación**
1. **Crea una `Casa`, un `Apartamento` y un `Chalet`.**  
2. **Imprime su información con `print()`.**  
3. **Prueba los métodos específicos de cada clase (`tiene_jardin()`, `es_penthouse()`, `tiene_piscina()`).**  
4. **Modifica algunos atributos después de la creación.**  
5. **Vuelve a imprimir los objetos y probar sus métodos.**

**Salida esperada:**
```python
Listado de viviendas:
Ubicación: Calle Mayor 123, Madrid | Tamaño: 150 m² | Precio: 250000€ | Tipo: Casa | Jardín: Sí
Ubicación: Avenida Central 45, Barcelona | Tamaño: 80 m² | Precio: 180000€ | Tipo: Apartamento | Piso: 5
Ubicación: Camino del Lago 12, Valencia | Tamaño: 200 m² | Precio: 400000€ | Tipo: Chalet | Piscina: Sí

Probando métodos específicos:
Esta casa tiene jardín
Este apartamento no es un penthouse
Este chalet tiene piscina

Modificando atributos y probando nuevamente:
Ubicación: Calle Mayor 123, Madrid | Tamaño: 150 m² | Precio: 260000€ | Tipo: Casa | Jardín: Sí
Ubicación: Avenida Central 45, Barcelona | Tamaño: 80 m² | Precio: 180000€ | Tipo: Apartamento | Piso: 7
Ubicación: Camino del Lago 12, Valencia | Tamaño: 200 m² | Precio: 400000€ | Tipo: Chalet | Piscina: No

Probando métodos nuevamente:
Esta casa tiene jardín
Este apartamento es un penthouse
Este chalet no tiene piscina
```

In [2]:
# Creo la clase padre Vivienda, que guarda lo común a cualquier tipo de vivienda
class Vivienda:
    def __init__(self, direccion, metros_cuadrados, precio):
        # Me guardo los datos básicos que comparten todas las viviendas
        self._direccion = direccion
        self._metros_cuadrados = metros_cuadrados
        self._precio = precio

    # Devuelvo una descripción general de la vivienda (las hijas la ampliarán)
    def __str__(self):
        return (
            f"Ubicación: {self._direccion} | "
            f"Tamaño: {self._metros_cuadrados} m² | "
            f"Precio: {self._precio}€"
        )


# Creo la clase Casa heredando de Vivienda y le añado el atributo jardín
class Casa(Vivienda):
    def __init__(self, direccion, metros_cuadrados, precio, jardin):
        # Reutilizo el constructor del padre para no repetir código
        super().__init__(direccion, metros_cuadrados, precio)
        self._jardin = jardin

    # Este método devuelve el texto exacto que pide el enunciado
    def tiene_jardin(self):
        if self._jardin:
            return "Esta casa tiene jardín"
        return "Esta casa no tiene jardín"

    # Aquí muestro todo en una sola línea como en la salida esperada
    def __str__(self):
        jardin_txt = "Sí" if self._jardin else "No"
        return f"{super().__str__()} | Tipo: Casa | Jardín: {jardin_txt}"


# Creo la clase Apartamento heredando de Vivienda y le añado el atributo piso
class Apartamento(Vivienda):
    def __init__(self, direccion, metros_cuadrados, precio, piso, ultimo_piso=7):
        super().__init__(direccion, metros_cuadrados, precio)
        self._piso = piso
        # Me guardo cuál considero el último piso para poder decidir si es penthouse
        self._ultimo_piso = ultimo_piso

    # Este método devuelve True si está en el último piso (tal como pide el enunciado)
    def es_penthouse(self):
        return self._piso == self._ultimo_piso

    # Para que salga exactamente el texto de la captura, lo convierto a frase
    def texto_penthouse(self):
        if self.es_penthouse():
            return "Este apartamento es un penthouse"
        return "Este apartamento no es un penthouse"

    def __str__(self):
        return f"{super().__str__()} | Tipo: Apartamento | Piso: {self._piso}"


# Creo la clase Chalet heredando de Vivienda y le añado el atributo piscina
class Chalet(Vivienda):
    def __init__(self, direccion, metros_cuadrados, precio, piscina):
        super().__init__(direccion, metros_cuadrados, precio)
        self._piscina = piscina

    def tiene_piscina(self):
        if self._piscina:
            return "Este chalet tiene piscina"
        return "Este chalet no tiene piscina"

    def __str__(self):
        piscina_txt = "Sí" if self._piscina else "No"
        return f"{super().__str__()} | Tipo: Chalet | Piscina: {piscina_txt}"



casa = Casa("Calle Mayor 123, Madrid", 150, 250000, True)
apartamento = Apartamento("Avenida Central 45, Barcelona", 80, 180000, 5, ultimo_piso=7)
chalet = Chalet("Camino del Lago 12, Valencia", 200, 400000, True)

print("Listado de viviendas:")
print(casa)
print(apartamento)
print(chalet)

print("\nProbando métodos específicos:")
print(casa.tiene_jardin())
print(apartamento.texto_penthouse())
print(chalet.tiene_piscina())

print("\nModificando atributos y probando nuevamente:")
casa._precio = 260000          # Aquí cambio el precio como en el ejemplo
apartamento._piso = 7          # Lo subo al último piso para que ahora sea penthouse
chalet._piscina = False        # Le quito la piscina para ver el cambio

print(casa)
print(apartamento)
print(chalet)

print("\nProbando métodos nuevamente:")
print(casa.tiene_jardin())
print(apartamento.texto_penthouse())
print(chalet.tiene_piscina())


Listado de viviendas:
Ubicación: Calle Mayor 123, Madrid | Tamaño: 150 m² | Precio: 250000€ | Tipo: Casa | Jardín: Sí
Ubicación: Avenida Central 45, Barcelona | Tamaño: 80 m² | Precio: 180000€ | Tipo: Apartamento | Piso: 5
Ubicación: Camino del Lago 12, Valencia | Tamaño: 200 m² | Precio: 400000€ | Tipo: Chalet | Piscina: Sí

Probando métodos específicos:
Esta casa tiene jardín
Este apartamento no es un penthouse
Este chalet tiene piscina

Modificando atributos y probando nuevamente:
Ubicación: Calle Mayor 123, Madrid | Tamaño: 150 m² | Precio: 260000€ | Tipo: Casa | Jardín: Sí
Ubicación: Avenida Central 45, Barcelona | Tamaño: 80 m² | Precio: 180000€ | Tipo: Apartamento | Piso: 7
Ubicación: Camino del Lago 12, Valencia | Tamaño: 200 m² | Precio: 400000€ | Tipo: Chalet | Piscina: No

Probando métodos nuevamente:
Esta casa tiene jardín
Este apartamento es un penthouse
Este chalet no tiene piscina


# Ejercicio 10

### 🏡 **Ejercicio: Ampliación del Sistema de Viviendas con Objetos Dentro de Objetos**

En este ejercicio ampliaremos nuestro sistema de viviendas, agregando **una clase `Propietario`** y haciendo que **cada vivienda tenga un propietario**, en lugar de solo atributos básicos.  

Aprenderemos a trabajar con **objetos dentro de objetos**, lo que nos permitirá estructurar la información de manera más organizada y realista.

##### **Características del ejercicio**

1. **Nueva Clase `Propietario`**  
   - `nombre` (nombre del propietario).  
   - `dni` (documento de identidad del propietario).  
   - `telefono` (teléfono de contacto).  
   - Método `__str__()` para mostrar la información del propietario.  

2. **Clase `Vivienda` (Clase Padre)**  
   - `direccion` (ubicación de la vivienda).  
   - `metros_cuadrados` (tamaño de la vivienda en m²).  
   - `precio` (precio de la vivienda en euros).  
   - `propietario` (**objeto de la clase `Propietario`**).  
   - Método `__str__()` que devuelve una descripción general de la vivienda con su propietario.  

3. **Clases Hijas que Heredan de `Vivienda`**  
   - **`Casa`** → Tiene un atributo adicional `jardin`.  
     - Método `tiene_jardin()`.  
   - **`Apartamento`** → Tiene un atributo adicional `piso`.  
     - Método `es_penthouse()`.  
   - **`Chalet`** → Tiene un atributo adicional `piscina`.  
     - Método `tiene_piscina()`.  

##### **Experimentación**
1. **Crea varios propietarios.**  
2. **Crea una `Casa`, un `Apartamento` y un `Chalet` asignando un propietario a cada una.**  
3. **Imprime su información con `print()`.**  
4. **Prueba los métodos específicos de cada clase (`tiene_jardin()`, `es_penthouse()`, `tiene_piscina()`).**  
5. **Modifica información de los propietarios.**  
6. **Vuelve a imprimir los objetos para ver los cambios reflejados.**  

**Salida esperada:**
```python
Listado de viviendas:
Ubicación: Calle Mayor 123, Madrid | Tamaño: 150 m² | Precio: 250000€
Propietario: Juan Pérez | DNI: 12345678A | Teléfono: 666123456 | Tipo: Casa | Jardín: Sí
Ubicación: Avenida Central 45, Barcelona | Tamaño: 80 m² | Precio: 180000€
Propietario: Laura Gómez | DNI: 87654321B | Teléfono: 644987321 | Tipo: Apartamento | Piso: 5
Ubicación: Camino del Lago 12, Valencia | Tamaño: 200 m² | Precio: 400000€
Propietario: Carlos Ramírez | DNI: 11223344C | Teléfono: 655789456 | Tipo: Chalet | Piscina: Sí

Probando métodos específicos:
Esta casa tiene jardín
Este apartamento no es un penthouse
Este chalet tiene piscina

Modificando propietario del apartamento...

Información del apartamento después de cambiar de propietario:
Ubicación: Avenida Central 45, Barcelona | Tamaño: 80 m² | Precio: 180000€
Propietario: Marta Fernández | DNI: 99887766D | Teléfono: 622555999 | Tipo: Apartamento | Piso: 5
```

In [15]:
# Esta clase representa al propietario de una vivienda
class Propietario:
    def __init__(self, nombre, dni, telefono):
        # Guardo los datos básicos de la persona
        self.nombre = nombre
        self.dni = dni
        self.telefono = telefono

    def __str__(self):
        # Devuelvo su información en formato texto
        return f"Propietario: {self.nombre} | DNI: {self.dni} | Teléfono: {self.telefono}"


# Esta es la clase base de todas las viviendas
class Vivienda:
    def __init__(self, direccion, metros_cuadrados, precio, propietario):
        # Aquí guardo los datos comunes a cualquier vivienda
        self.direccion = direccion
        self.metros_cuadrados = metros_cuadrados
        self.precio = precio
        self.propietario = propietario  # Aquí estoy guardando un objeto Propietario

    def __str__(self):
        # Devuelvo la información general de la vivienda
        return (f"Ubicación: {self.direccion} | "
                f"Tamaño: {self.metros_cuadrados} m² | "
                f"Precio: {self.precio}€")


# Casa hereda de Vivienda y añade si tiene jardín o no
class Casa(Vivienda):
    def __init__(self, direccion, metros_cuadrados, precio, propietario, jardin):
        # Uso super para aprovechar el constructor de la clase padre
        super().__init__(direccion, metros_cuadrados, precio, propietario)
        self.jardin = jardin

    def tiene_jardin(self):
        # Este método solo existe en Casa
        if self.jardin:
            return "Esta casa tiene jardín"
        else:
            return "Esta casa no tiene jardín"

    def __str__(self):
        # Amplío la información general añadiendo los datos específicos
        jardin_texto = "Sí" if self.jardin else "No"
        return (super().__str__() + "\n" +
                f"{self.propietario} | Tipo: Casa | Jardín: {jardin_texto}")


# Apartamento también hereda de Vivienda y añade el número de piso
class Apartamento(Vivienda):
    def __init__(self, direccion, metros_cuadrados, precio, propietario, piso):
        super().__init__(direccion, metros_cuadrados, precio, propietario)
        self.piso = piso

    def es_penthouse(self):
        # Considero que es penthouse si está en el piso 7 o superior
        return self.piso >= 7

    def __str__(self):
        return (super().__str__() + "\n" +
                f"{self.propietario} | Tipo: Apartamento | Piso: {self.piso}")


# Chalet hereda de Vivienda y añade si tiene piscina
class Chalet(Vivienda):
    def __init__(self, direccion, metros_cuadrados, precio, propietario, piscina):
        super().__init__(direccion, metros_cuadrados, precio, propietario)
        self.piscina = piscina

    def tiene_piscina(self):
        if self.piscina:
            return "Este chalet tiene piscina"
        else:
            return "Este chalet no tiene piscina"

    def __str__(self):
        piscina_texto = "Sí" if self.piscina else "No"
        return (super().__str__() + "\n" +
                f"{self.propietario} | Tipo: Chalet | Piscina: {piscina_texto}")


# Ahora creo varios propietarios
prop1 = Propietario("Juan Pérez", "12345678A", "666123456")
prop2 = Propietario("Laura Gómez", "87654321B", "644987321")
prop3 = Propietario("Carlos Ramírez", "11223344C", "655789456")

# Creo las viviendas asociando cada propietario
casa = Casa("Calle Mayor 123, Madrid", 150, 250000, prop1, True)
apartamento = Apartamento("Avenida Central 45, Barcelona", 80, 180000, prop2, 5)
chalet = Chalet("Camino del Lago 12, Valencia", 200, 400000, prop3, True)

print("Listado de viviendas:\n")
print(casa)
print(apartamento)
print(chalet)

print("\nProbando métodos específicos:")
print(casa.tiene_jardin())
print("Este apartamento es un penthouse" if apartamento.es_penthouse() else "Este apartamento no es un penthouse")
print(chalet.tiene_piscina())

# Ahora cambio el propietario del apartamento
print("\nModificando propietario del apartamento...\n")

nuevo_prop = Propietario("Marta Fernández", "99887766D", "622555999")
apartamento.propietario = nuevo_prop

print("Información del apartamento después de cambiar de propietario:\n")
print(apartamento)


Listado de viviendas:

Ubicación: Calle Mayor 123, Madrid | Tamaño: 150 m² | Precio: 250000€
Propietario: Juan Pérez | DNI: 12345678A | Teléfono: 666123456 | Tipo: Casa | Jardín: Sí
Ubicación: Avenida Central 45, Barcelona | Tamaño: 80 m² | Precio: 180000€
Propietario: Laura Gómez | DNI: 87654321B | Teléfono: 644987321 | Tipo: Apartamento | Piso: 5
Ubicación: Camino del Lago 12, Valencia | Tamaño: 200 m² | Precio: 400000€
Propietario: Carlos Ramírez | DNI: 11223344C | Teléfono: 655789456 | Tipo: Chalet | Piscina: Sí

Probando métodos específicos:
Esta casa tiene jardín
Este apartamento no es un penthouse
Este chalet tiene piscina

Modificando propietario del apartamento...

Información del apartamento después de cambiar de propietario:

Ubicación: Avenida Central 45, Barcelona | Tamaño: 80 m² | Precio: 180000€
Propietario: Marta Fernández | DNI: 99887766D | Teléfono: 622555999 | Tipo: Apartamento | Piso: 5
